- name: Waka - Readme
  uses: athul/waka-readme@0.1.3
  with:
    # GitHub access token with Repo scope
    GH_TOKEN: ${{ secrets.GH_TOKEN }} # default is ${{ github.token }}
    # Your Wakatime API Key
    WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
    # Your GitHub username
    USERNAME: jiangxinlei # optional, default is ${{ github.repository_owner }}
    # Displays the week number and days in Readme as title
    SHOW_TITLE: "true" # optional
